create table page_contents (
    id bigint generated by default as identity,
    page_type varchar(30) not null,
    title varchar(120) not null,
    subtitle varchar(180),
    description text,
    display_order integer not null,
    constraint pk_page_contents primary key (id),
    constraint uk_page_contents_type unique (page_type)
);

create table page_heroes (
    id bigint generated by default as identity,
    page_id bigint not null,
    headline varchar(160) not null,
    sub_headline varchar(200),
    description text,
    primary_action_label varchar(80),
    primary_action_url varchar(500),
    constraint pk_page_heroes primary key (id),
    constraint uk_page_heroes_page_id unique (page_id),
    constraint fk_page_heroes_page_id foreign key (page_id) references page_contents (id)
);

create table page_sections (
    id bigint generated by default as identity,
    page_id bigint not null,
    section_key varchar(60) not null,
    title varchar(120) not null,
    description text,
    display_order integer not null,
    constraint pk_page_sections primary key (id),
    constraint fk_page_sections_page_id foreign key (page_id) references page_contents (id)
);

create table page_section_items (
    section_id bigint not null,
    item_order integer not null,
    item varchar(500) not null,
    constraint pk_page_section_items primary key (section_id, item_order),
    constraint fk_page_section_items_section_id foreign key (section_id) references page_sections (id)
);

create table page_skills (
    id bigint generated by default as identity,
    page_id bigint not null,
    name varchar(80) not null,
    category varchar(80) not null,
    level varchar(40),
    display_order integer not null,
    constraint pk_page_skills primary key (id),
    constraint fk_page_skills_page_id foreign key (page_id) references page_contents (id)
);

create table page_experiences (
    id bigint generated by default as identity,
    page_id bigint not null,
    company varchar(120) not null,
    role varchar(120) not null,
    period varchar(80),
    description text,
    display_order integer not null,
    constraint pk_page_experiences primary key (id),
    constraint fk_page_experiences_page_id foreign key (page_id) references page_contents (id)
);

create table page_experience_highlights (
    experience_id bigint not null,
    highlight_order integer not null,
    highlight varchar(500) not null,
    constraint pk_page_experience_highlights primary key (experience_id, highlight_order),
    constraint fk_page_experience_highlights_experience_id foreign key (experience_id) references page_experiences (id)
);

create table project_items (
    id bigint generated by default as identity,
    page_id bigint not null,
    title varchar(120) not null,
    summary varchar(240) not null,
    description text,
    repository_url varchar(500),
    service_url varchar(500),
    display_order integer not null,
    constraint pk_project_items primary key (id),
    constraint fk_project_items_page_id foreign key (page_id) references page_contents (id)
);

create table project_item_tech_stacks (
    project_id bigint not null,
    tech_stack_order integer not null,
    tech_stack varchar(80) not null,
    constraint pk_project_item_tech_stacks primary key (project_id, tech_stack_order),
    constraint fk_project_item_tech_stacks_project_id foreign key (project_id) references project_items (id)
);
