create table servers (
    id bigint generated by default as identity,
    name varchar(120) not null,
    host varchar(255) not null,
    location varchar(120),
    status varchar(30) not null,
    cpu_usage_percent double precision,
    memory_usage_percent double precision,
    disk_usage_percent double precision,
    last_checked_at timestamp,
    constraint pk_servers primary key (id)
);

create table monitored_services (
    id bigint generated by default as identity,
    server_id bigint not null,
    name varchar(120) not null,
    description varchar(500),
    base_url varchar(500) not null,
    status varchar(30) not null,
    uptime_percentage double precision,
    response_time_ms bigint,
    last_checked_at timestamp,
    constraint pk_monitored_services primary key (id),
    constraint fk_monitored_services_server_id foreign key (server_id) references servers (id)
);
