create table llm_servers (
    id bigint generated by default as identity,
    name varchar(120) not null,
    host varchar(255) not null,
    mac_address varchar(30),
    chat_endpoint_url varchar(500),
    status varchar(30) not null,
    last_wake_requested_at timestamp,
    last_checked_at timestamp,
    constraint pk_llm_servers primary key (id)
);
