alter table servers add column server_role varchar(80);
alter table servers add column metrics_url varchar(500);
alter table servers add column enabled boolean;
alter table servers add column display_order integer;

update servers
set server_role = 'unknown',
    metrics_url = 'http://' || host || ':9100/metrics',
    enabled = true,
    display_order = id
where server_role is null;

alter table servers alter column server_role set not null;
alter table servers alter column metrics_url set not null;
alter table servers alter column enabled set not null;
alter table servers alter column display_order set not null;

create table monitoring_snapshots (
    id bigint generated by default as identity,
    server_id bigint not null,
    status varchar(30) not null,
    cpu_usage_percent double precision,
    memory_usage_percent double precision,
    disk_usage_percent double precision,
    uptime_seconds bigint,
    load_average1m double precision,
    temperature_celsius double precision,
    cpu_total_seconds double precision,
    cpu_idle_seconds double precision,
    collected_at timestamp not null,
    error_message text,
    constraint pk_monitoring_snapshots primary key (id),
    constraint fk_monitoring_snapshots_server_id foreign key (server_id) references servers (id)
);

create index idx_monitoring_snapshots_server_collected_at
    on monitoring_snapshots (server_id, collected_at);

create index idx_monitoring_snapshots_collected_at
    on monitoring_snapshots (collected_at);
